"""add_consecutive_zero_count

Revision ID: 3522f8b6e283
Revises: 50fb02b298b3
Create Date: 2026-02-18 19:38:32.839219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3522f8b6e283'
down_revision: Union[str, Sequence[str], None] = '50fb02b298b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consecutive_zero_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_column('consecutive_zero_count')

    # ### end Alembic commands ###
