"""initial schema

Revision ID: 50fb02b298b3
Revises: 
Create Date: 2026-02-18 13:29:09.857656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50fb02b298b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('management_company', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('rentcafe_property_id', sa.String(), nullable=True),
    sa.Column('rentcafe_api_token', sa.String(), nullable=True),
    sa.Column('last_scrape_status', sa.String(), server_default='never', nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('unit_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(), nullable=False),
    sa.Column('bed_type', sa.String(), nullable=False),
    sa.Column('non_canonical', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('rent_cents', sa.Integer(), nullable=False),
    sa.Column('availability_date', sa.String(), nullable=False),
    sa.Column('floor_plan_name', sa.String(), nullable=True),
    sa.Column('floor_plan_url', sa.String(), nullable=True),
    sa.Column('baths', sa.String(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('scrape_run_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'unit_number', name='uq_unit_building_number')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index('ix_units_availability_date', ['availability_date'], unique=False)
        batch_op.create_index('ix_units_bed_type', ['bed_type'], unique=False)
        batch_op.create_index('ix_units_building_id', ['building_id'], unique=False)
        batch_op.create_index('ix_units_rent_cents', ['rent_cents'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index('ix_units_rent_cents')
        batch_op.drop_index('ix_units_building_id')
        batch_op.drop_index('ix_units_bed_type')
        batch_op.drop_index('ix_units_availability_date')

    op.drop_table('units')
    op.drop_table('scrape_runs')
    op.drop_table('buildings')
    # ### end Alembic commands ###
